// Generated by CoffeeScript 1.6.3
(function() {
  var Db;

  Db = (function() {
    function Db(config, tokenMgr, log) {
      var Mongo, MySql, mongoose;
      if (config.mysql.enable) {
        log.info('Initializing MySql...');
        MySql = require('./_mysql').MySql;
        this.mysql = new MySql(config.mysql, tokenMgr, log);
      }
      if (config.mongo.enable) {
        log.info('Initializing MongoDB...');
        Mongo = require('./_mongo').Mongo;
        mongoose = require('mongoose');
        mongoose.connect(config.mongo.options);
        this.mongo = new Mongo(config.mongo, log);
      }
    }

    return Db;

  })();

  exports.Db = Db;

}).call(this);
