// Generated by CoffeeScript 1.6.3
(function() {
  var Db;

  Db = (function() {
    function Db(kit) {
      var Mongo, MySql, config, log, mongoose, tokenMgr;
      log = kit.services.logger.log;
      config = kit.services.config;
      tokenMgr = kit.services.tokenMgr;
      if (config.db.mysql.enable) {
        log.info('Initializing MySql...');
        MySql = require('./_mysql').MySql;
        this.mysql = new MySql(config.db.mysql, tokenMgr, log);
      }
      if (config.db.mongo.enable) {
        log.info('Initializing MongoDB...');
        Mongo = require('./_mongo').Mongo;
        mongoose = require('mongoose');
        mongoose.connect(config.db.mongo.options);
        this.mongo = new Mongo(config.db.mongo, log);
      }
    }

    return Db;

  })();

  exports.Db = Db;

}).call(this);
