// Generated by CoffeeScript 1.6.3
(function() {
  var Db, PreLoader, User, Wrapper, bunyan, config, db, log, ping, pre_loader, restify, server, user, wrapper;

  restify = require('restify');

  bunyan = require('bunyan');

  config = (require('./lib/config'))();

  log = bunyan.createLogger(config.log);

  Db = require('./lib/db').Db;

  db = new Db(config.db, log);

  PreLoader = require('./lib/pre_loader').PreLoader;

  pre_loader = new PreLoader(db, log);

  Wrapper = require('./lib/route_wrapper').Wrapper;

  wrapper = new Wrapper(db, pre_loader, log);

  ping = require('./routes/ping');

  User = require('./routes/user').User;

  user = new User(db, wrapper, log);

  server = restify.createServer({
    log: log
  });

  server.use(function(req, res, next) {
    res.setHeader('Access-Control-Allow-Credentials', 'true');
    res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*');
    return next();
  });

  server.use(restify.queryParser());

  server.use(restify.bodyParser());

  server.use(restify.requestLogger());

  server.use(function(req, res, next) {
    req.log.info('ROUTE:', req.url, req.method);
    req.log.info('PARAMS:', req.params);
    return next();
  });

  server.get('/ping/:name', ping);

  server.get('/User/:usid', user.get);

  server.post('/User', user.createUser);

  server.listen(config.api.port, function() {
    return log.info('Server listening at', server.url);
  });

}).call(this);
