// Generated by CoffeeScript 1.6.3
(function() {
  var AuthParser, AuthRoute, Db, Kit, Logger, PreLoader, TokenMgr, User, Workout, Wrapper, config, kit, log, restify, s_use, server;

  Db = require('./lib/db').Db;

  Kit = require('./lib/kit').Kit;

  s_use = require('./lib/server_use');

  config = (require('./lib/config'))();

  Logger = require('./lib/logger').Logger;

  Wrapper = require('./lib/route_wrapper').Wrapper;

  TokenMgr = require('./lib/token_manager').TokenMgr;

  PreLoader = require('./lib/pre_loader').PreLoader;

  AuthParser = require('./lib/authorizationParser').AuthParser;

  User = require('./routes/r_user').User;

  Workout = require('./routes/r_workout').Workout;

  AuthRoute = require('./routes/r_auth').AuthRoute;

  kit = new Kit;

  kit.add_service('config', config);

  kit.new_service('logger', Logger);

  kit.new_service('tokenMgr', TokenMgr);

  kit.new_service('db', Db);

  kit.new_service('pre_loader', PreLoader);

  kit.new_service('wrapper', Wrapper);

  kit.new_service('authParser', AuthParser);

  kit.new_route_service('auth', AuthRoute);

  kit.new_route_service('user', User);

  kit.new_route_service('workout', Workout);

  restify = require('restify');

  log = kit.services.logger.log;

  server = restify.createServer({
    log: kit.services.logger.log
  });

  server.use(s_use.set_response_headers);

  server.use(restify.queryParser());

  server.use(restify.bodyParser());

  server.use(restify.requestLogger());

  server.use(kit.services.authParser.parseAuthorization);

  server.use(s_use.debug_request);

  server.post('/Auth', kit.routes.auth.authenticate);

  server.get('/User/:usid', kit.routes.user.get);

  server.post('/User', kit.routes.user.createUser);

  server.get('/Workout', kit.routes.workout.get);

  server.post('/Workout', kit.routes.workout.createWorkout);

  server.listen(config.api.port, function() {
    return log.info('Server listening at', server.url);
  });

}).call(this);
