// Generated by CoffeeScript 1.9.2
(function() {
  var RestifyRequest, RestifyResponse;

  RestifyRequest = (function() {
    function RestifyRequest(opts) {
      this.headers = (opts != null ? opts.headers : void 0) || {};
      this.url = (opts != null ? opts.url : void 0) || {};
      this.method = (opts != null ? opts.method : void 0) || {};
      this.statusCode = (opts != null ? opts.statusCode : void 0) || {};
      this.params = (opts != null ? opts.params : void 0) || {};
    }

    return RestifyRequest;

  })();

  exports.RestifyRequest = RestifyRequest;

  RestifyResponse = (function() {
    function RestifyResponse(opts) {
      this.headers = (opts != null ? opts.headers : void 0) || {};
    }

    RestifyResponse.prototype.setHeader = function(nm, val) {
      return this.headers[nm] = val;
    };

    RestifyResponse.prototype.send = function(data) {
      return this.data = data;
    };

    return RestifyResponse;

  })();

  exports.RestifyResponse = RestifyResponse;

}).call(this);
