// Generated by CoffeeScript 1.4.0
var MobileInset,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

MobileInset = (function(_super) {

  __extends(MobileInset, _super);

  function MobileInset(Epic, view_nm) {
    var ss;
    ss = {
      selected_device: 'iphone-6',
      orientation: 'v'
    };
    MobileInset.__super__.constructor.call(this, Epic, view_nm, ss);
  }

  MobileInset.prototype.action = function(act, p) {
    var f, i, m, r;
    f = "action:" + act;
    _log2(f, p);
    r = {};
    i = new window.EpicMvc.Issue(this.Epic, this.view_nm, act);
    m = new window.EpicMvc.Issue(this.Epic, this.view_nm, act);
    switch (act) {
      case "choose_device":
        this.selected_device = p.device;
        this.invalidateTables(true);
        break;
      case "toggle_orientation":
        this.orientation = this.orientation === 'v' ? 'h' : 'v';
        this.invalidateTables(true);
        break;
      default:
        return MobileInset.__super__.action.call(this, act, p);
    }
    return [r, i, m];
  };

  MobileInset.prototype.loadTable = function(tbl_nm) {
    var debug, row;
    debug = "loadTable:" + tbl_nm;
    switch (tbl_nm) {
      case 'Opts':
        row = {
          device: this.selected_device,
          orientation: this.orientation
        };
        return this.Table[tbl_nm] = [row];
      default:
        return MobileInset.__super__.loadTable.call(this, tbl_nm);
    }
  };

  return MobileInset;

})(window.EpicMvc.ModelJS);

window.EpicMvc.Model.MobileInset = MobileInset;
