// Generated by CoffeeScript 1.9.2
(function() {
  var E, LongPoll, _, _log,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  E = require('../lib/error');

  _ = require('lodash');

  _log = false;

  LongPoll = (function() {
    LongPoll.deps = {
      services: ['logger', 'config', 'push', 'pollMgr'],
      config: 'api[longPollTimeout,authReqForPoll]'
    };

    function LongPoll(kit) {
      this.LongPollRequest = bind(this.LongPollRequest, this);
      var ref;
      _log = kit.services.logger.log;
      this.config = kit.services.config;
      this.push = kit.services.push;
      this.pollMgr = kit.services.pollMgr;
      this.setTimeout = ((ref = kit.services.test) != null ? ref.mock_setTimeout : void 0) || setTimeout;
      this.long_timeout = this.config.api.longPollTimeout;
      this.safe_timeout = this.long_timeout + 5000;
      _log.info('Setting LongPoll Timeout to:', this.long_timeout);
      this.endpoints = {
        poll: {
          verb: 'post',
          route: '/Poll',
          use: true,
          wrap: 'simple_wrap',
          version: {
            any: this.LongPollRequest
          },
          auth_required: this.config.api.authReqForPoll
        }
      };
    }

    LongPoll.prototype.LongPollRequest = function(req, res, next) {
      var arg, f, i, id, len, p, ref, use_doc;
      use_doc = {
        params: {
          state: '{}',
          listen: '{}'
        },
        response: {
          state: '{}',
          listen: '{}',
          sync: '{}'
        }
      };
      if (req === 'use') {
        return use_doc;
      }
      f = 'LongPoll:_LongPollRequest:';
      _log = req.log;
      p = req.params;
      id = req.id();
      ref = ['state', 'listen'];
      for (i = 0, len = ref.length; i < len; i++) {
        arg = ref[i];
        if (!(arg in p)) {
          res.send(new E.MissingArg(arg));
          return next();
        }
      }
      _log.debug(f, 'state:', p.state, 'listen:', p.listen);
      req.connection.pause();
      req.connection.setTimeout(this.safe_timeout);
      req.on('close', (function(_this) {
        return function() {
          return _this.pollMgr.PollerClosed(id);
        };
      })(this));
      this.pollMgr.AddPoller(id, req, res, p.listen, p.state, this.long_timeout);
      return next();
    };

    return LongPoll;

  })();

  exports.LongPoll = LongPoll;

}).call(this);
