// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, User,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Promise = require('bluebird');

  User = (function() {
    User.deps = {
      services: ['error'],
      mysql: ['user']
    };

    function User(kit) {
      this._pl_user = bind(this._pl_user, this);
      this._update_profile = bind(this._update_profile, this);
      this._view_profile = bind(this._view_profile, this);
      this.sdb = kit.services.db.mysql;
      this.E = kit.services.error;
      this.endpoints = {
        get: {
          verb: 'get',
          route: '/User/:usid',
          use: true,
          wrap: 'default_wrap',
          version: {
            any: this._view_profile
          },
          sql_conn: true,
          auth_required: true,
          pre_load: {
            user: this._pl_user
          }
        },
        update_profile: {
          verb: 'put',
          route: '/User/:usid/updateprofile',
          use: true,
          wrap: 'default_wrap',
          version: {
            any: this._update_profile
          },
          sql_conn: true,
          sql_tx: true,
          auth_required: true,
          pre_load: {
            user: this._pl_user
          }
        }
      };
    }

    User.prototype._view_profile = function(ctx, pre_loaded) {
      var f, success, use_doc, user;
      use_doc = {
        params: {},
        response: {
          success: 'bool',
          users: 'list'
        }
      };
      if (ctx === 'use') {
        return use_doc;
      }
      f = 'User:_get:';
      success = false;
      if (pre_loaded.auth_id !== pre_loaded.user.id) {
        throw new this.E.AccessDenied('USER:VIEW_PROFILE:AUTH_ID');
      }
      user = [pre_loaded.user];
      success = true;
      return {
        send: {
          success: success,
          user: user
        }
      };
    };

    User.prototype._update_profile = function(ctx, pre_loaded) {
      var f, new_user_values, nm, p, updatable_fields, use_doc, val;
      use_doc = {
        params: {
          fnm: 'S',
          lnm: 'S',
          website: 'S',
          avatar_path: 'S',
          avatar_thumb: 'S',
          prog_lang: 'S',
          skill_lvl: 'S'
        },
        response: {
          success: 'bool',
          updated_user: 'object'
        }
      };
      if (ctx === 'use') {
        return use_doc;
      }
      p = ctx.p;
      if (pre_loaded.auth_id !== pre_loaded.user.id) {
        throw new this.E.AccessDenied('USER:UPDATE_PROFILE:AUTH_ID');
      }
      f = 'User:_update_profile:';
      updatable_fields = ['fnm', 'lnm', 'website', 'avatar_path', 'avatar_thumb', 'prog_lang', 'skill_lvl'];
      new_user_values = {};
      for (nm in p) {
        val = p[nm];
        if (indexOf.call(updatable_fields, nm) >= 0) {
          new_user_values[nm] = val;
        }
      }
      return Promise.resolve().bind(this).then(function() {
        ctx.log.debug(f, new_user_values);
        return this.sdb.user.update_by_ident_id(ctx, pre_loaded.user.id, new_user_values);
      }).then(function(db_result) {
        ctx.log.debug(f, 'got profile update result:', db_result);
        if (db_result.affectedRows !== 1) {
          throw new this.E.DbError('User Update Failed');
        }
        new_user_values.id = pre_loaded.user.id;
        return {
          send: {
            success: true,
            updated_user: new_user_values
          }
        };
      });
    };

    User.prototype._pl_user = function(ctx, pre_loaded) {
      var f, id;
      f = 'User:_pl_user:';
      ctx.log.debug(f, ctx.p);
      id = ctx.p.usid === 'me' ? pre_loaded.auth_id : ctx.p.usid;
      return Promise.resolve().bind(this).then(function() {
        return this.sdb.user.get_by_ident_id(ctx, id);
      }).then(function(db_rows) {
        if (db_rows.length !== 1) {
          throw new this.E.NotFoundError('User');
        }
        return db_rows[0];
      });
    };

    return User;

  })();

  exports.User = User;

}).call(this);
