// Generated by CoffeeScript 1.9.2
(function() {
  var SqlUser;

  SqlUser = (function() {
    SqlUser.deps = {};

    function SqlUser(core, kit) {
      this.db = core;
      this.table = 'profile';
      this.ident_tbl = 'ident';
      this.schema = {
        get_by_ident_id: ['i.id', 'i.eml', 'e.fnm', 'e.lnm', 'e.cr', 'e.mo', 'e.website', 'e.avatar_path', 'e.avatar_thumb', 'e.prog_lang', 'e.skill_lvl'],
        update_by_ident_id: ['fnm', 'lnm', 'website', 'avatar_path', 'avatar_thumb', 'prog_lang', 'skill_lvl'],
        Create: ['ident_id', 'fnm', 'lnm']
      };
      this.db.method_factory(this, 'SqlUser');
    }

    SqlUser.prototype.get_by_ident_id = function(ctx, ident_id) {
      var f, sql;
      f = "SqlUser:get_by_ident_id:";
      sql = "SELECT " + (this.schema.get_by_ident_id.join(',')) + "\nFROM " + this.ident_tbl + " i LEFT OUTER JOIN " + this.table + " e\n	 ON i.id= e.ident_id \nWHERE i.id= ? AND i.di= 0 AND (e.di= 0 OR e.id IS NULL)";
      return (this.db.sqlQuery(ctx, sql, [ident_id])).then(function(db_rows) {
        return db_rows;
      });
    };

    return SqlUser;

  })();

  exports.SqlUser = SqlUser;

}).call(this);
