// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, SqlTrip;

  Promise = require('bluebird');

  SqlTrip = (function() {
    SqlTrip.deps = {};

    function SqlTrip(core, kit) {
      this.db = core;
      this.table = 'trips';
      this.schema = {
        create: ['auth_ident_id', 'ident_id', 'token', 'domain', 'json', 'void', 'expires'],
        update_by_id: ['json', 'void', 'expires', 'returned', 'ident_id'],
        get_by_token: ['*'],
        get_by_id: ['*']
      };
      this.db.method_factory(this, 'SqlTrip');
    }

    SqlTrip.prototype.get_by_token = function(ctx, token) {
      var f;
      f = "DB:SqlTrip:get_by_token:";
      ctx.log.debug(f, token);
      return Promise.resolve().bind(this).then(function() {
        var sql;
        sql = "SELECT " + (this.schema.get_by_token.join(',')) + " \nFROM " + this.table + "\nWHERE token= ? AND di= 0";
        return this.db.sqlQuery(ctx, sql, [token]);
      }).then(function(db_rows) {
        return db_rows;
      });
    };

    return SqlTrip;

  })();

  exports.SqlTrip = SqlTrip;

}).call(this);
