// Generated by CoffeeScript 1.4.0
(function() {
  var AccessDenied, DbError, InvalidArg, MissingArg, MongoDbError, NotFoundError, OAuthError, ServerError, restify, util;

  restify = require('restify');

  util = require('util');

  InvalidArg = function(message) {
    restify.RestError.call(this, {
      statusCode: 400,
      body: {
        error: 'InvalidParam',
        message: message
      },
      constructorOpt: InvalidArg
    });
    return this.name = 'Invalid Argument';
  };

  util.inherits(InvalidArg, restify.RestError);

  exports.InvalidArg = InvalidArg;

  MissingArg = function(message) {
    restify.RestError.call(this, {
      statusCode: 400,
      body: {
        error: 'MissingParam',
        message: message
      },
      constructorOpt: MissingArg
    });
    return this.name = 'Missing Argument';
  };

  util.inherits(MissingArg, restify.RestError);

  exports.MissingArg = MissingArg;

  NotFoundError = function(token, message) {
    restify.RestError.call(this, {
      statusCode: 404,
      body: {
        error: token,
        message: message
      },
      constructorOpt: NotFoundError
    });
    return this.name = 'Resource Not Found';
  };

  util.inherits(NotFoundError, restify.RestError);

  exports.NotFoundError = NotFoundError;

  OAuthError = function(code, error, message) {
    var body;
    body = message ? {
      error: error,
      message: message
    } : {
      error: error
    };
    restify.RestError.call(this, {
      statusCode: code,
      restCode: 'OAuthError',
      message: 'Invalid OAuth Request',
      body: body,
      constructorOpt: OAuthError
    });
    return this.name = 'OAuth 2.0 Error';
  };

  util.inherits(OAuthError, restify.RestError);

  exports.OAuthError = OAuthError;

  AccessDenied = function(token, message) {
    restify.RestError.call(this, {
      statusCode: 403,
      body: {
        error: token,
        message: message
      },
      constructorOpt: AccessDenied
    });
    return this.name = 'Access Denied';
  };

  util.inherits(AccessDenied, restify.RestError);

  exports.AccessDenied = AccessDenied;

  DbError = function(token) {
    restify.RestError.call(this, {
      statusCode: 500,
      restCode: 'DatabaseError',
      body: {
        error: token
      },
      constructorOpt: DbError
    });
    return this.name = 'Database Error';
  };

  util.inherits(DbError, restify.RestError);

  exports.DbError = DbError;

  ServerError = function(token, message) {
    restify.RestError.call(this, {
      statusCode: 500,
      restCode: 'ServerError',
      body: {
        error: token,
        message: message
      },
      constructorOpt: ServerError
    });
    return this.name = 'Server Error';
  };

  util.inherits(ServerError, restify.RestError);

  exports.ServerError = ServerError;

  MongoDbError = function(message) {
    restify.RestError.call(this, {
      statusCode: 500,
      restCode: 'MongoDbError',
      message: message,
      body: {
        error: 'mongo_error',
        message: message
      },
      constructorOpt: MongoDbError
    });
    return this.name = 'Mongo Database Error';
  };

  util.inherits(MongoDbError, restify.RestError);

  exports.MongoDbError = MongoDbError;

}).call(this);
