// Generated by CoffeeScript 1.6.3
(function() {
  var InvalidArg, restify, util;

  restify = require('restify');

  util = require('util');

  InvalidArg = function(message, data) {
    restify.RestError.call(this, {
      statusCode: 400,
      restCode: 'InvalidArgument',
      message: message,
      body: {
        code: 'InvalidArgument',
        message: message,
        data: data
      },
      constructorOpt: InvalidArg
    });
    return this.name = 'Invalid Argument';
  };

  util.inherits(InvalidArg, restify.RestError);

  exports.InvalidArg = InvalidArg;

}).call(this);
