// Generated by CoffeeScript 1.9.2
(function() {
  var Event, EventEmitter,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = require('events').EventEmitter;

  Event = (function(superClass) {
    extend(Event, superClass);

    Event.deps = {};

    function Event(kit) {
      this.log = kit.services.logger.log;
    }

    return Event;

  })(EventEmitter);

  exports.Event = Event;

}).call(this);
