// Generated by CoffeeScript 1.4.0
var Kit;

Kit = (function() {

  function Kit() {
    this.services = {};
    this.routes = {};
  }

  Kit.prototype.add_service = function(name, obj) {
    return this.services[name] = obj;
  };

  Kit.prototype.new_service = function(name, constructor, args) {
    var Obj, _t;
    _t = this;
    Obj = function() {
      var arg, c_args, _i, _len, _ref;
      c_args = [_t];
      _ref = args != null ? args : [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        arg = _ref[_i];
        c_args.push(arg);
      }
      return constructor.apply(this, c_args);
    };
    Obj.prototype = constructor.prototype;
    return this.services[name] = new Obj;
  };

  Kit.prototype.add_route_service = function(name, obj) {
    return this.routes[name] = obj;
  };

  Kit.prototype.new_route_service = function(name, constructor, args) {
    var Obj, _t;
    _t = this;
    Obj = function() {
      var arg, c_args, _i, _len, _ref;
      c_args = [_t];
      _ref = args != null ? args : [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        arg = _ref[_i];
        c_args.push(arg);
      }
      return constructor.apply(this, c_args);
    };
    Obj.prototype = constructor.prototype;
    return this.routes[name] = new Obj;
  };

  return Kit;

})();

exports.Kit = Kit;
