// Generated by CoffeeScript 1.6.3
(function() {
  var Kit;

  Kit = (function() {
    function Kit() {
      this.services = {};
      this.routes = {};
    }

    Kit.prototype.add_service = function(name, obj) {
      return this.services[name] = obj;
    };

    Kit.prototype.new_service = function(name, constructor, args) {
      var Obj, _services;
      _services = this.services;
      Obj = function() {
        var arg, c_args, _i, _len, _ref;
        c_args = [_services];
        _ref = args != null ? args : [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          arg = _ref[_i];
          c_args.push(arg);
        }
        return constructor.apply(this, c_args);
      };
      Obj.prototype = constructor.prototype;
      return this.services[name] = new Obj;
    };

    Kit.prototype.new_route_service = function(name, constructor) {
      var Obj, _services;
      _services = this.services;
      Obj = function() {
        return constructor.apply(this, [_services]);
      };
      Obj.prototype = constructor.prototype;
      return this.routes[name] = new Obj;
    };

    return Kit;

  })();

  exports.Kit = Kit;

}).call(this);
