// Generated by CoffeeScript 1.9.2
(function() {
  var Lamd, MongoClient, Promise, _,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Promise = require('bluebird');

  _ = require('lodash');

  MongoClient = require('mongodb').MongoClient;

  Lamd = (function() {
    Lamd.deps = {
      services: ['logger'],
      config: 'lamd{connect_url,connect_db,options}'
    };

    function Lamd(kit) {
      this._read = bind(this._read, this);
      this.read_deep = bind(this.read_deep, this);
      this.read = bind(this.read, this);
      this.write_deep = bind(this.write_deep, this);
      this.write = bind(this.write, this);
      this.server_init = bind(this.server_init, this);
      var f;
      f = 'Lamd:constructor';
      this.config = kit.services.config.lamd;
      this.log = kit.services.logger.log;
      this.db = false;
      this.collection_debug = false;
      this.collection_deep_debug = false;
    }

    Lamd.prototype.GetLog = function(ctx) {
      var fn, i, lamd_logger, len, method, ref;
      ctx.lamd_logger = {
        debug: []
      };
      lamd_logger = {};
      ref = ['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'child'];
      fn = (function(_this) {
        return function(method) {
          return lamd_logger[method] = function(f, data) {
            return _this._log(ctx, method, f, data);
          };
        };
      })(this);
      for (i = 0, len = ref.length; i < len; i++) {
        method = ref[i];
        fn(method);
      }
      return lamd_logger;
    };

    Lamd.prototype._log = function(ctx, method, f, data) {
      if (this.config.to_debug) {
        this.log.debug(f + (method !== 'debug' ? method : ''), data);
      }
      if (method === 'child') {
        return;
      }
      return ctx.lamd_logger.debug.push({
        method: method,
        f: f,
        data: data
      });
    };

    Lamd.prototype.server_init = function(kit) {
      var f, server;
      f = 'Lamd:server_init:';
      server = kit.services.server.server;
      return Promise.resolve().bind(this).then(function() {
        var ref;
        return MongoClient.connect(this.config.connect_url, (ref = this.config.options) != null ? ref : {});
      }).then(function(client) {
        if (client != null) {
          this.log.debug('Successfully connected to MongoDB database.');
        }
        if (client == null) {
          throw new Error(f + 'MongoDB connection is empty');
        }
        this.log.debug(f, _.pick(client.s, ['url', 'options']));
        this.db = client.db(this.config.connect_db);
        this.log.debug(f, _.pick(this.db, ['databaseName', 'options']));
        this.collection_debug = this.db.collection('debug');
        return this.collection_deep_debug = this.db.collection('deep_debug');
      });
    };

    Lamd.prototype.write = function(data) {
      var err, f;
      f = 'Lamd:write:';
      try {
        return this._write(data);
      } catch (_error) {
        err = _error;
        return this.log.warn(f + 'err', err);
      }
    };

    Lamd.prototype._write = function(data) {
      var f;
      f = 'Lamd:_write:';
      return this.collection_debug.insertOne(data, {
        forceServerObjectId: true
      }, (function(_this) {
        return function(err, result) {
          if (err != null) {
            return _this.log.debug(f, {
              err: err,
              result: result
            });
          }
          if (_this.config.to_debug) {
            return _this.log.debug(f, data);
          }
        };
      })(this));
    };

    Lamd.prototype.write_deep = function(ctx) {
      var err, f;
      f = 'Lamd:write:';
      try {
        return this._write_deep(ctx);
      } catch (_error) {
        err = _error;
        return this.log.warn(f + 'err', err);
      }
    };

    Lamd.prototype._write_deep = function(ctx) {
      var data, f;
      f = 'Lamd:_write_deep:';
      data = ctx.lamd_logger.debug;
      return this.collection_deep_debug.insertOne({
        _id: ctx.lamd.req_uuid,
        lamd: ctx.lamd,
        debug: data
      }, {}, (function(_this) {
        return function(err, result) {
          if (err != null) {
            return _this.log.debug(f, {
              err: err,
              result: result
            });
          }
        };
      })(this));
    };

    Lamd.prototype.read = function(ctx, method, query, projection, options, hint, sort) {
      return this._read(ctx, this.collection_debug, method, query, projection, options, hint, sort);
    };

    Lamd.prototype.read_deep = function(ctx, method, query, projection, options, hint, sort) {
      return this._read(ctx, this.collection_deep_debug, method, query, projection, options, hint, sort);
    };

    Lamd.prototype._read = function(ctx, collection, method, query, projection, options, hint, sort) {
      var f;
      f = 'Lamd-Custom:read:';
      if (method === "find") {
        query = collection.find(query).project(projection);
        if (sort) {
          query = query.sort(sort);
        }
        query = query.limit(100);
        if (hint) {
          query = query.hint(hint);
        }
        query = query.toArray();
        return query.then((function(_this) {
          return function(docs) {
            if (_this.config.to_debug) {
              _this.log.debug(f, {
                docs: docs
              });
            }
            return docs;
          };
        })(this));
      } else if (method === "aggregate") {
        query = collection.aggregate(query, options);
        query = query.toArray();
        return query.then((function(_this) {
          return function(docs) {
            if (_this.config.to_debug) {
              _this.log.debug(f, {
                docs: docs
              });
            }
            return docs;
          };
        })(this));
      }
    };

    return Lamd;

  })();

  exports.Lamd = Lamd;

}).call(this);
