// Generated by CoffeeScript 1.9.2
(function() {
  var Logger, bunyan,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  bunyan = require('bunyan');

  Logger = (function() {
    Logger.deps = {
      services: ['config']
    };

    function Logger(kit) {
      this.server_use = bind(this.server_use, this);
      this.config = kit.services.config;
      this.log = bunyan.createLogger(this.config.log);
      this.log.info('Logger Initialized...');
    }

    Logger.prototype.server_use = function(req, res, next) {
      var nm, ref, ref1, val;
      if ((ref = this.config.log_opts) != null ? ref.no_route_logs : void 0) {
        return next();
      }
      req.log.info('ROUTE:', req.method, req.url);
      ref1 = req.params;
      for (nm in ref1) {
        val = ref1[nm];
        if (nm !== '_') {
          req.log.info('PARAM:', nm + ':', val);
        }
      }
      return next();
    };

    return Logger;

  })();

  exports.Logger = Logger;

}).call(this);
