// Generated by CoffeeScript 1.6.3
(function() {
  var Logger, bunyan;

  bunyan = require('bunyan');

  Logger = (function() {
    function Logger(kit) {
      var config;
      config = kit.services.config;
      this.log = bunyan.createLogger(config.log);
      this.log.info('Logger Initialized...');
    }

    return Logger;

  })();

  exports.Logger = Logger;

}).call(this);
