// Generated by CoffeeScript 1.9.2
(function() {
  var Postgres_Lamd, Promise, _, psql,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Promise = require('bluebird');

  psql = require('pg');

  _ = require('lodash');

  Postgres_Lamd = (function() {
    Postgres_Lamd.deps = {
      mysql: ['lamd'],
      services: ['logger'],
      config: 'plamd'
    };

    function Postgres_Lamd(kit) {
      this.write = bind(this.write, this);
      var f;
      f = 'PLamd:constructor';
      this.config = kit.services.config.lamd;
      this.log = kit.services.logger.log;
      this.sdb = kit.services.db.mysql;
    }

    Postgres_Lamd.prototype.server_init = function(kit) {
      var f;
      f = 'PLamd:server_init';
      return Promise.resolve().bind(this).then(function() {
        return this.sdb.core.Acquire();
      }).then(function(c) {
        return this.ctx.conn = c;
      });
    };

    Postgres_Lamd.prototype.write = function(data) {
      var f;
      f = 'PLamd:write:';
      return Promise.resolve().bind(this).then(function() {
        return this.sdb.lamd.create(this.ctx, data);
      });
    };

    return Postgres_Lamd;

  })();

  exports.Postgres_Lamd = Postgres_Lamd;

}).call(this);
