// Generated by CoffeeScript 1.6.3
(function() {
  var PreLoader, Q;

  Q = require('q');

  PreLoader = (function() {
    function PreLoader(kit) {
      kit.logger.log.info('Initializing Pre-Loader...');
      this.db = kit.db;
      this.log = kit.logger.log;
    }

    PreLoader.prototype.load_user = function(conn, usid) {
      var _this = this;
      this.log.debug('PreLoader:load_user:', usid);
      return Q.resolve().then(function() {
        var sql;
        sql = 'SELECT * FROM t1_users WHERE id= ? AND disposal= 0';
        return _this.db.mysql.core.sqlQuery(conn, sql, [usid]);
      }).then(function(db_rows) {
        if (db_rows.length === 0) {
          return false;
        }
        return db_rows[0];
      });
    };

    return PreLoader;

  })();

  exports.PreLoader = PreLoader;

}).call(this);
