// Generated by CoffeeScript 1.6.3
(function() {
  var E, Push, PushSet, Q, sdb;

  Q = require('q');

  E = require('./error');

  sdb = false;

  Push = (function() {
    function Push(kit) {
      kit.services.logger.log.info('Initializing Push Service...');
      sdb = kit.services.db.mysql;
      this.log = kit.services.logger.log;
      this.pset_by_name = {};
    }

    Push.prototype.GetPushSet = function(ctx, clear_pset, nm, description) {
      var f, pset, _log, _ref;
      f = 'Push:GetPushSet';
      _log = ctx.log;
      _log.debug(f, clear_pset, nm);
      pset = (_ref = this.pset_by_name[nm]) != null ? _ref : false;
      if (pset && !clear_pset) {
        return pset;
      }
      return Q.resolve().then(function() {
        return sdb.core.AcquireTxConn(ctx);
      }).then(function() {
        return sdb.pset.read_or_insert(ctx, nm);
      }).then(function(existing_pset) {
        pset = existing_pset;
        if (!clear_pset) {
          return false;
        }
        return sdb.pset.clean(ctx, pset.id);
      }).then(function() {
        return sdb.core.sqlQuery(ctx, 'COMMIT');
      }).then(function(db_result) {
        sdb.core.release(ctx.conn);
        return nm;
      });
    };

    return Push;

  })();

  PushSet = (function() {
    function PushSet(pset) {
      this.pset = pset;
      this.p_items = {};
    }

    PushSet.prototype.itemChange = function(xref, verb, before, after, tbl_id, tbl) {};

    PushSet.prototype.getItem = function(xref) {};

    PushSet.prototype._createItem = function(xref) {};

    return PushSet;

  })();

  exports.Push = Push;

}).call(this);
