// Generated by CoffeeScript 1.4.0
(function() {
  var E, Q, RoleManager,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Q = require('q');

  E = require('./error');

  RoleManager = (function() {

    function RoleManager(kit) {
      this.log = kit.services.logger.log;
      this.log.info('Initializing Role Manager...');
      this.config = kit.services.config;
      this.role_def = this.config.roles.role_def;
      this.permit_def = this.config.roles.permit_def;
      this.sift_def = this.config.roles.sift_def;
      this.lFunc = this.config.route_prefix_length.api;
    }

    RoleManager.prototype.SetCtx = function(ctx, roleTk, resource_overide) {
      var f, permit_nm;
      f = 'RoleManager:SetCtx:';
      ctx.log.debug(f, roleTk, resource_overide);
      ctx.role_def = this.role_def[roleTk];
      ctx.resource = resource_overide != null ? resource_overide : (((ctx.req.url.split('?'))[0].slice(this.lFunc(ctx.p.Version))).split('/'))[1];
      if (!ctx.role_def[ctx.resource]) {
        throw new E.ServerError('ROLEMGR:RESOURCE_NOT_IN_ROLEDEF', ctx.resource);
      }
      permit_nm = ctx.role_def[ctx.resource].permit;
      return ctx.permit = permit_nm === false ? false : this.permit_def[ctx.resource][permit_nm];
    };

    RoleManager.prototype.CheckSift = function(ctx, resource) {
      var f, _ref;
      f = 'RoleManager:CheckSift:';
      if (!ctx.role_def[resource]) {
        throw new E.AccessDenied('ROLE:SIFT:RESOURCE_NOT_IN_ROLEDEF', resource);
      }
      if (!this.sift_def[resource]) {
        throw new E.AccessDenied('ROLE:SIFT:RESOURCE_NOT_IN_SIFTDEF', resource);
      }
      if (_ref = ctx.role_def[resource].SIFT, __indexOf.call(this.sift_def[resource], _ref) < 0) {
        throw new E.AccessDenied('ROLE:SIFT:SIFT_LIST');
      }
      return ctx.role_def[resource].SIFT;
    };

    RoleManager.prototype.CheckTalent = function(roleTk, wanted_talent) {
      var f, _ref, _ref1;
      f = 'RoleManager:CheckTalent:';
      this.log.debug(f, {
        roleTk: roleTk,
        wanted_talent: wanted_talent
      });
      if (__indexOf.call((_ref = (_ref1 = this.role_def[roleTk]) != null ? _ref1.talent : void 0) != null ? _ref : [], wanted_talent) < 0) {
        throw new E.AccessDenied(f + 'TALENT_LIST');
      }
    };

    RoleManager.prototype.GetTalentedRoles = function(talent) {
      var def, f, role, talented_roles, _ref, _ref1;
      f = 'RoleManager:GetTalentedRoles:';
      this.log.debug(f, talent);
      talented_roles = [];
      _ref = this.role_def;
      for (role in _ref) {
        def = _ref[role];
        if (__indexOf.call((_ref1 = def.talent) != null ? _ref1 : [], talent) >= 0) {
          talented_roles.push(role);
        }
      }
      return talented_roles;
    };

    return RoleManager;

  })();

  exports.RoleManager = RoleManager;

}).call(this);
