// Generated by CoffeeScript 1.6.3
(function() {
  var Q, Router, log_map, use_map,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Q = require('q');

  log_map = {
    get: 'GET ',
    post: 'POST',
    put: 'PUT ',
    del: 'DEL '
  };

  use_map = {
    get: 'GET',
    post: 'POST',
    put: 'PUT',
    del: 'DEL'
  };

  Router = (function() {
    function Router(kit) {
      this.route_usage = __bind(this.route_usage, this);
      kit.services.logger.log.info('Initializing Router...');
      this.log = kit.services.logger.log;
      this.usage = {};
      this.pfx = kit.services.config.route_prefix.api;
      this.server = kit.services.server;
    }

    Router.prototype.add_route = function(verb, route, func) {
      var v, verbs, _i, _len, _results;
      this.usage[use_map[verb] + ': ' + route] = func('use');
      verbs = [verb];
      if (verb === 'del' || verb === 'put') {
        verbs.push('post');
      }
      _results = [];
      for (_i = 0, _len = verbs.length; _i < _len; _i++) {
        v = verbs[_i];
        this.log.info('\t', log_map[v], route);
        _results.push(this.server[v](this.pfx + '' + route, func));
      }
      return _results;
    };

    Router.prototype.route_usage = function() {
      var _this = this;
      return this.server.get(this.pfx, function(q, r, n) {
        r.send(_this.usage);
        return n();
      });
    };

    return Router;

  })();

  exports.Router = Router;

}).call(this);
