// Generated by CoffeeScript 1.8.0
(function() {
  var Stats, getOrMakeChildObject, _log;

  _log = false;

  getOrMakeChildObject = function() {
    var a, c, i, o, _i, _len;
    o = arguments[0];
    for (i = _i = 0, _len = arguments.length; _i < _len; i = ++_i) {
      a = arguments[i];
      c = o[arguments[i]];
      if (!c) {
        c = o[arguments[i]] = {};
      }
      o = c;
    }
    return o;
  };

  Stats = (function() {
    function Stats(server, log) {
      log.info('Initializing Server Stats...');
      _log = log;
      this._reqs = {};
      server.on('after', function(req, res, route, error) {
        var n, status;
        status = res.statusCode;
        req.log.debug('server.after: returning [', status, '] for req:', route ? route.spec.path : req.url);
        if (!route) {
          return req.log.debug('Stats-Unknown: [', status, '] ', req.url);
        }
        if (typeof status === 'undefined') {
          status = 0;
        }
        n = getOrMakeChildObject(self._reqs, route ? route.spec.method + ' ' + route.spec.path : 'unknown');
        if (isNaN(n[status])) {
          return n[status] = 1;
        } else {
          return n[status]++;
        }
      });
    }

    Stats.prototype.getStats = function() {
      return {
        name: 'restify',
        reqs: this._reqs
      };
    };

    return Stats;

  })();

  exports.Stats = Stats;

}).call(this);
