// Generated by CoffeeScript 1.6.3
(function() {
  exports.debug_request = function(req, res, next) {
    var p;
    req.log.info('ROUTE:', req.url, req.method);
    for (p in req.params) {
      req.log.info('PARAM:', req.params[p]);
    }
    return next();
  };

  exports.set_response_headers = function(req, res, next) {
    res.setHeader('Access-Control-Allow-Credentials', 'true');
    res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*');
    return next();
  };

}).call(this);
