// Generated by CoffeeScript 1.6.3
(function() {
  exports.debug_request = function(req, res, next) {
    var nm, val, _ref;
    req.log.info('ROUTE:', req.url, req.method);
    _ref = req.params;
    for (nm in _ref) {
      val = _ref[nm];
      req.log.info('PARAM:', nm + ':', val);
    }
    return next();
  };

  exports.set_response_headers = function(req, res, next) {
    res.setHeader('Access-Control-Allow-Credentials', 'true');
    res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*');
    return next();
  };

}).call(this);
