// Generated by CoffeeScript 1.9.2
(function() {
  var Util, _, _log;

  _ = require('lodash');

  _log = false;

  Util = (function() {
    function Util(kit) {
      _log = kit.services.logger.log;
    }

    Util.prototype.Diff = function(first, second) {
      var after, before, f, nm, val;
      f = 'Util:Diff:';
      if (_.isEmpty(first)) {
        return [first, second];
      }
      before = {};
      after = {};
      for (nm in first) {
        val = first[nm];
        if (!(first[nm] !== second[nm])) {
          continue;
        }
        if (typeof val === 'object') {
          if (_.isEqual(first[nm], second[nm])) {
            continue;
          }
        }
        before[nm] = first[nm];
        after[nm] = second[nm];
      }
      return [before, after];
    };

    return Util;

  })();

  exports.Util = Util;

}).call(this);
