// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  var ViewExe;

  ViewExe = (function() {
    function ViewExe(Epic, loadStrategy, content_watch) {
      var frames, ix, nm;
      this.Epic = Epic;
      this.loadStrategy = loadStrategy;
      this.content_watch = content_watch;
      this.dynamicParts = [];
      frames = this.Epic.oAppConf.getFrames();
      this.frames = (function() {
        var j, len, ref, results;
        ref = ((function() {
          var results1;
          results1 = [];
          for (nm in frames) {
            results1.push(nm);
          }
          return results1;
        })()).sort();
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          ix = ref[j];
          results.push(frames[ix]);
        }
        return results;
      })();
      this.Epic.log1(':ViewExec', this.frames);
      this.dynamicMap = {};
    }

    ViewExe.prototype.init = function(template, page) {
      var j, len, nm, ref, v;
      this.template = template;
      this.page = page;
      this.Epic.log2(':ViewExe.init T:' + this.template, 'P:' + this.page, ((function() {
        var j, len, ref, results;
        ref = (this.Epic.getInstance('Pageflow')).getStepPath();
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          v = ref[j];
          results.push(v);
        }
        return results;
      }).call(this)).join('/'));
      this.instance = this.Epic.nextCounter();
      this.oTemplate = this.loadStrategy.template(this.template);
      this.oPage = this.loadStrategy.page(this.page);
      this.pageStack = [];
      ref = this.frames;
      for (j = 0, len = ref.length; j < len; j++) {
        nm = ref[j];
        this.pageStack.push(this.loadStrategy.template(nm));
      }
      this.pageStack.push(this.oTemplate, this.oPage);
      this.stack = [];
      this.TagExe = this.Epic.getInstance('Tag');
      this.TagExe.resetForNextRequest();
      this.current = null;
      this.dynamicParts = [
        {
          defer: [],
          parent: 0
        }
      ];
      this.dynamicMap = {};
      return this.activeDynamicPartIx = 0;
    };

    ViewExe.prototype.part = function(ix) {
      return this.dynamicParts[ix || this.activeDynamicPartIx];
    };

    ViewExe.prototype.doDynamicPart = function(ix, instance) {
      var f, j, len, old_dynamic_ix, part, ref, watch;
      f = ':ViewExe.doDynamicPart:' + ix;
      if (instance !== this.instance) {
        return;
      }
      part = this.part(ix);
      if (part.pending === false) {
        return;
      }
      part.stamp = new Date().getTime();
      part.pending = false;
      part.defer = [];
      $('#' + part.id).html('Changing...');
      old_dynamic_ix = this.activeDynamicPartIx;
      this.activeDynamicPartIx = ix;
      this.TagExe.resetForNextRequest(part.state);
      $('#' + part.id).html(this.run(this.loadStrategy.part(part.name)));
      this.doDeferPart(part);
      ref = this.content_watch;
      for (j = 0, len = ref.length; j < len; j++) {
        watch = ref[j];
        watch('#' + part.id);
      }
      return this.activeDynamicPartIx = old_dynamic_ix;
    };

    ViewExe.prototype.pushDefer = function(code) {
      return this.part().defer.push(code);
    };

    ViewExe.prototype.doDeferPart = function(part) {
      var j, len, ref, v;
      ref = part.defer;
      for (j = 0, len = ref.length; j < len; j++) {
        v = ref[j];
        eval(v.code);
      }
      return true;
    };

    ViewExe.prototype.doDefer = function() {
      var j, len, part, ref;
      ref = this.dynamicParts;
      for (j = 0, len = ref.length; j < len; j++) {
        part = ref[j];
        this.doDeferPart(part);
      }
      return true;
    };

    ViewExe.prototype.haveTableRefrence = function(view_nm, tbl_nm) {
      var base, nm;
      if (this.activeDynamicPartIx === 0) {
        return;
      }
      nm = (this.Epic.getInstanceNm(view_nm)) + ':' + tbl_nm;
      if ((base = this.dynamicMap)[nm] == null) {
        base[nm] = [];
      }
      return this.dynamicMap[nm].push(this.activeDynamicPartIx);
    };

    ViewExe.prototype.addDynamicPart = function(info) {
      var f;
      f = ':ViewExe.addDynamicPart';
      if (this.activeDynamicPartIx !== 0) {
        alert('Nested dynamic parts not really supported just now.');
      }
      this.dynamicParts.push({
        name: info.name,
        id: info.id,
        delay: info.delay,
        state: info.state,
        defer: [],
        parent: this.activeDynamicPartIx,
        pending: false,
        stamp: new Date().getTime()
      });
      return this.activeDynamicPartIx = this.dynamicParts.length - 1;
    };

    ViewExe.prototype.invalidateTables = function(view_nm, tbl_nms) {
      var delay, f, inst, instance, ix, ix_list, j, k, len, len1, nm, now, part, ref, sched, sofar, tbl_nm;
      f = ':ViewExe.invalidateTables';
      sched = [];
      if (this.dynamicParts.length === 1) {
        return 'no dynamic parts';
      }
      if (this.Epic.inClick) {
        return 'in click';
      }
      ix_list = {};
      inst = this.Epic.getInstanceNm(view_nm);
      for (j = 0, len = tbl_nms.length; j < len; j++) {
        tbl_nm = tbl_nms[j];
        nm = inst + ':' + tbl_nm;
        if (nm in this.dynamicMap) {
          ref = this.dynamicMap[nm];
          for (k = 0, len1 = ref.length; k < len1; k++) {
            ix = ref[k];
            ix_list[ix] = true;
          }
        }
      }
      now = new Date().getTime();
      for (ix in ix_list) {
        ix = Number(ix);
        part = this.part(ix);
        if (part.pending === false) {
          sofar = now - part.stamp;
          delay = sofar > part.delay ? 0 : part.delay - sofar;
          instance = this.instance;
          (function(_this) {
            return (function(ix, instance) {
              part.pending = window.setTimeout((function() {
                return _this.doDynamicPart(ix, instance);
              }), delay);
              return sched.push(ix);
            });
          })(this)(ix, instance);
        }
      }
      return sched;
    };

    ViewExe.prototype.run = function(current, dynoInfo) {
      var e, out, ref;
      if (current == null) {
        current = this.pageStack.shift(0);
      }
      this.stack.push([this.current, this.activeDynamicPartIx]);
      this.current = current;
      if (dynoInfo) {
        this.addDynamicPart(dynoInfo);
      }
      try {
        out = this.doAllParts(0);
      } catch (_error) {
        e = _error;
        if (this.stack.length > 0) {
          throw e;
        }
        out = e.message + "<pre>\n" + e.stack + "</pre>";
      } finally {
        ref = this.stack.pop(), this.current = ref[0], this.activeDynamicPartIx = ref[1];
      }
      return out;
    };

    ViewExe.prototype.includePage = function() {
      return this.run(this.pageStack.shift(0));
    };

    ViewExe.prototype.includePart = function(nm, dynoInfo) {
      if (dynoInfo !== false) {
        dynoInfo.name = nm;
      }
      return this.run(this.loadStrategy.part(nm), dynoInfo);
    };

    ViewExe.prototype.doAllParts = function(parts_inx) {
      var attr, first, j, len, out, ref, tag, tag_self;
      parts_inx = Number(parts_inx);
      out = '';
      if (parts_inx === 0) {
        out += this.handleIt(this.current[0]);
        parts_inx = this.current.length - 1;
        first = false;
      } else {
        first = true;
        out += this.handleIt(this.current[parts_inx + 3]);
      }
      ref = this.current[parts_inx];
      for (j = 0, len = ref.length; j < len; j++) {
        tag_self = ref[j];
        if (first) {
          first = false;
          continue;
        }
        tag = this.current[tag_self + 1];
        attr = this.current[tag_self + 2];
        out += this.TagExe['Tag_' + tag]({
          parts: tag_self,
          attrs: attr
        });
        out += this.handleIt(this.current[this.current[tag_self][0]]);
      }
      return out;
    };

    ViewExe.prototype.handleIt = function(text_n_vars) {
      var args, cmd, i, j, out, ref, ref1;
      if (typeof text_n_vars === 'string') {
        return text_n_vars;
      }
      out = text_n_vars[0];
      for (i = j = 1, ref = text_n_vars.length; j < ref; i = j += 2) {
        ref1 = text_n_vars[i], cmd = ref1[0], args = ref1[1];
        out += this.TagExe[cmd].apply(this.TagExe, args);
        out += text_n_vars[i + 1];
      }
      return out;
    };

    return ViewExe;

  })();

  if (typeof window !== "undefined" && window !== null) {
    window.EpicMvc.ViewExe = ViewExe;
  } else {
    module.exports = function(w) {
      return w.EpicMvc.ViewExe = ViewExe;
    };
  }

}).call(this);
