// Generated by CoffeeScript 1.4.0

module.exports = {
  api: {
    port: 9500
  },
  db: {
    mysql: {
      enable: true,
      pool: {
        host: 'localhost',
        port: 3306,
        user: 'root',
        password: 'DV-mobile2012',
        database: 'blueprint'
      }
    }
  }
};
