// Generated by CoffeeScript 1.4.0
var config, fileExists, fs, path, _, _log;

fs = require('fs');

path = require('path');

_ = require('lodash');

config = require('./default');

_log = console.log;

fileExists = function(filepath) {
  try {
    fs.statSync(filepath);
  } catch (e) {
    return false;
  }
  return true;
};

module.exports = function() {
  var configDir, env, envPath, execDir;
  env = process.env.npm_config_env;
  configDir = process.env.npm_config_config_dir;
  execDir = process.cwd();
  _log('Environment specified:', env);
  _log('Config Dir specified:', configDir);
  envPath = path.join(execDir, configDir, env + '.js');
  _log('Env Config Path:', envPath);
  if (fileExists(envPath)) {
    _log('Environment configuration found:', envPath);
    _.merge(config, require(envPath));
  } else {
    _log('Environment specific configuration file not loaded. Using default configuration.');
  }
  config.env = env;
  config.processDir = execDir;
  return config;
};
