/*
	Push Database Schema
*/

CREATE TABLE push_item (
		id		SERIAL			PRIMARY KEY /* https://www.postgresqltutorial.com/postgresql-serial/ */
	,	di		SMALLINT   		DEFAULT 0 NOT NULL /* disposal - 0:none,1:disabled,2:purge*/
	,	cr		TIMESTAMP(0)		DEFAULT CURRENT_TIMESTAMP /* row created */
	,	mo		TIMESTAMP(0)		DEFAULT CURRENT_TIMESTAMP /* row modified */

	,	route_slice		VARCHAR(128) NOT NULL
	,	payload			json /* {resource, id, verb, old_fields, new_fields} */
);