// Generated by CoffeeScript 1.4.0
(function() {
  var E, MCore, Q, checkForHexRegExp, mongoose,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Q = require('q');

  E = require('../../error');

  mongoose = require('mongoose');

  checkForHexRegExp = new RegExp("^[0-9a-fA-F]{24}$");

  MCore = (function() {

    function MCore(log) {
      this.log = log;
      this.save = __bind(this.save, this);

    }

    MCore.prototype.isObjectId = function(n) {
      return checkForHexRegExp.test(n);
    };

    MCore.prototype.create = function(model, opts) {
      return (Q.ninvoke(model, 'create', opts)).then(function(doc) {
        return doc;
      });
    };

    MCore.prototype.save = function(doc) {
      return (Q.ninvoke(doc, 'save')).then(function() {
        return null;
      });
    };

    MCore.prototype.update = function(model, where, set, opts) {
      if (!opts) {
        opts = {};
      }
      return (Q.ninvoke(doc, 'update', where, set, opts)).then(function(numberAffected, raw) {
        return {
          numberAffected: numberAffected,
          raw: raw
        };
      });
    };

    MCore.prototype.findByIdAndUpdate = function(id, set, opts) {
      if (!opts) {
        opts = {};
      }
      return (Q.ninvoke(doc, 'findByIdAndUpdate', id, set, opts)).then(function(new_doc) {
        return new_doc;
      });
    };

    MCore.prototype.find = function(model, opts, pjn) {
      return (Q.ninvoke(model, 'find', opts, pjn)).then(function(docs) {
        return docs;
      });
    };

    MCore.prototype.findOne = function(model, opts, pjn) {
      return (Q.ninvoke(model, 'findOne', opts, pjn)).then(function(doc) {
        return doc;
      });
    };

    MCore.prototype.findById = function(model, id) {
      return (Q.ninvoke(model, 'findById', id)).then(function(doc) {
        return doc;
      });
    };

    return MCore;

  })();

  exports.MCore = MCore;

}).call(this);
