// Generated by CoffeeScript 1.9.2
(function() {
  var Util, chai;

  chai = require('chai');

  Util = require('../lib/Util');

  chai.should();

  describe('Routes', function() {
    return it('should be true', function(done) {
      return (Util.db.SqlQuery('SELECT * FROM ident')).then(function(db_rows) {
        return done();
      })["catch"](function(err) {
        console.log({
          err: err
        });
        return done(err);
      });
    });
  });

}).call(this);
