// Generated by CoffeeScript 1.9.2
(function() {
  var Util, chai;

  chai = require('chai');

  Util = require('../lib/Util');

  chai.should();

  describe('Routes', function() {
    return it('should be true', function() {
      return (Util.db.SqlQuery('SELECT * FROM ident')).then(function(db_rows) {
        return true;
      });
    });
  });

}).call(this);
