// Generated by CoffeeScript 1.6.3
(function() {
  var MySql, SqlAuth, SqlCore, SqlPSet, SqlPSetItem, SqlPSetItemChange, SqlToken, SqlTrip, SqlUser;

  SqlCore = require('./sql_core').SqlCore;

  SqlUser = require('./sql_user').SqlUser;

  SqlToken = require('./sql_token').SqlToken;

  SqlAuth = require('./sql_auth').SqlAuth;

  SqlPSet = require('./sql_pset').SqlPSet;

  SqlTrip = require('./sql_trip').SqlTrip;

  SqlPSetItem = require('./sql_pset_item').SqlPSetItem;

  SqlPSetItemChange = require('./sql_pset_item_change').SqlPSetItemChange;

  MySql = (function() {
    function MySql(config, tokenMgr, log) {
      this.core = new SqlCore(config.options, log);
      this.auth = new SqlAuth(this.core, log);
      this.user = new SqlUser(this.core, log);
      this.pset = new SqlPSet(this.core, log);
      this.token = new SqlToken(this.core, tokenMgr, log);
      this.pset = new SqlPSet(this.core, log);
      this.pset_item = new SqlPSetItem(this.core, log);
      this.pset_item_change = new SqlPSetItemChange(this.core, log);
    }

    return MySql;

  })();

  exports.MySql = MySql;

}).call(this);
