// Generated by CoffeeScript 1.6.3
(function() {
  var MySql, SqlCore, SqlUser;

  SqlCore = require('./sql_core').SqlCore;

  SqlUser = require('./sql_user').SqlUser;

  MySql = (function() {
    function MySql(config, log) {
      this.core = new SqlCore(config.options, log);
      this.user = new SqlUser(this.core, log);
    }

    return MySql;

  })();

  exports.MySql = MySql;

}).call(this);
