// Generated by CoffeeScript 1.8.0
(function() {
  var E, Q, SqlTrip;

  Q = require('q');

  E = require('../../error');

  SqlTrip = (function() {
    function SqlTrip(core, kit) {
      this.log = kit.services.logger.log;
      this.db = core;
      this.table = 'trips';
      this.schema = {
        create: ['auth_ident_id', 'ident_id', 'token', 'domain', 'json', 'void', 'expires'],
        update_by_id: ['json', 'void', 'expires', 'returned', 'ident_id'],
        get_by_token: ['*'],
        get_by_id: ['*']
      };
      this.db.method_factory(this, 'SqlTrip');
    }

    SqlTrip.prototype.get_by_token = function(ctx, token) {
      var f;
      f = "DB:SqlTrip:get_by_token:";
      this.log.debug(f, token);
      return Q.resolve().then((function(_this) {
        return function() {
          var sql;
          sql = 'SELECT ' + (_this.schema.get_by_token.join(',')) + ' FROM ' + _this.table + ' WHERE token= ? AND di= 0';
          return _this.db.sqlQuery(ctx, sql, [token]);
        };
      })(this)).then(function(db_rows) {
        return db_rows;
      });
    };

    return SqlTrip;

  })();

  exports.SqlTrip = SqlTrip;

}).call(this);
